services:
  webserver:
    build:
      context: "docker/webserver"
    container_name: "portfolio-nextjs"
    restart: "always"
    ports:
      - "3000:3000"
    volumes:
      - ./app/:/var/www/html
